website/music/urls.py
from django.conf.urls import include,url
from . import views

app_name = 'music'

urlpatterns = [
	#/music/
    url(r'^$', views.index, name='index'),
	#/music/[number]
	url(r'^(?P<album_id>[0-9]+)/$',views.detail, name='detail'),

	#/music/[number]/favorite/
	url(r'^(?P<album_id>[0-9]+)/favorite/$',views.favorite, name='favorite'),
]

website/website/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

website/music/models.py
from __future__ import unicode_literals

from django.db import models

class Album(models.Model):
	artist = models.CharField(max_length=500)
	album_title = models.CharField(max_length=250)
	album_genre = models.CharField(max_length=100)
	album_logo = models.CharField(max_length=1000)

	def __str__(self):
		return self.album_title + '-' + self.artist

class Song(models.Model):
	album= models.ForeignKey(Album, on_delete=models.CASCADE)
	file_type = models.CharField(max_length=10)
	song_title = models.CharField(max_length=250)
	is_favourite = models.BooleanField(default=False)

	def __str__(self):
		return self.song_title

website/music/views.py
from django.shortcuts import render, get_object_or_404
from models import Album

def index(request):
	all_albums= Album.objects.all()
	context = {'all_albums' : all_albums}
	return render(request, 'music/index.html', context)

def detail(request,album_id):
	album = get_object_or_404(Album, id=album_id)
	return render(request, 'music/details.html', {'album' : album})

def favorite(request,album_id):
	album = get_object_or_404(Album, id=album_id)
	try:
		selected_song=album.song_set.get(id=request.POST['song'])
	except (KeyError, Song.DoesNotExist):
		return render(request, 'music/details.html', {'album' : album, error_message:"You didn't select a valid song"})
	else:
		selected_song.is_favourite = True
		selected_song.save()
		return render(request, 'music/details.html', {'album' : album})

website/music/templates/music/details.html
<center><img src= {{ album.album_logo }} style='height:200px;width:200px'></center>
<h1 align='middle'>{{ album.album_title}}</h1>
<h3 align='middle'>{{ album.artist}}</h3>

{% if error_message %}
	<strong>{{ error_message }}</strong>
{% endif %}

<form action="{% url 'music:favorite' album.id %}" method= "post">
	{% csrf_token %}
	{% for song in album.song_set.all %}
		<input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}">
		<label for="song{{ forloop.counter }}">
			{{ song.song_title }}
			{% if song.is_favourite %}
				<img src="http://wfarm4.dataknet.com/static/resources/icons/set24/f308dfb391.png">
			{% endif %}
		</label><br>
	{% endfor %}
	<input type="submit" value="Favorite">
</form>

website/music/templates/music/index.html
{% if all_albums %}
	<h1>Bollywood Albums</h1>
	<ul>
		{% for album in all_albums %}
		<li><a href="{% url 'music:detail' album.id %}">{{ album.album_title }}</a></li>
		{% endfor %}
	</ul>
{% else %}
	<h2>No albums</h2>
{% endif %}